import { pgTable, boolean, uuid, timestamp } from 'drizzle-orm/pg-core'

export const amenity = pgTable('amenity', {
  id: uuid('id').primaryKey().defaultRandom(),
  ac: boolean('ac').default(false),
  barberShop: boolean('barberShop').default(false),
  bbqGrill: boolean('bbqGrill').default(false),
  beachAccess: boolean('beachAccess').default(false),
  beautySalon: boolean('beautySalon').default(false),
  bikes: boolean('bikes').default(false),
  childcareFacilities: boolean('childcareFacilities').default(false),
  cinemaRoom: boolean('cinemaRoom').default(false),
  convinienceStore: boolean('convinienceStore').default(false),
  dedicatedWorkspace: boolean('dedicatedWorkspace').default(false),
  dryer: boolean('dryer').default(false),
  elevator: boolean('elevator').default(false),
  excerciseEquipment: boolean('excerciseEquipment').default(false),
  fireExtinguisher: boolean('fireExtinguisher').default(false),
  firePit: boolean('firePit').default(false),
  firstAidKit: boolean('firstAidKit').default(false),
  fitnessCenter: boolean('fitnessCenter').default(false),
  freeParking: boolean('freeParking').default(false),
  fridge: boolean('fridge').default(false),
  gamingRoom: boolean('gamingRoom').default(false),
  hammocks: boolean('hammocks').default(false),
  heating: boolean('heating').default(false),
  hotTub: boolean('hotTub').default(false),
  indoorFireplace: boolean('indoorFireplace').default(false),
  kayaks: boolean('kayaks').default(false),
  kitchen: boolean('kitchen').default(false),
  lakeAccess: boolean('lakeAccess').default(false),
  miniFridge: boolean('miniFridge').default(false),
  monoxideAlarm: boolean('monoxideAlarm').default(false),
  outdoorDiningArea: boolean('outdoorDiningArea').default(false),
  outdoorShower: boolean('outdoorShower').default(false),
  paidParking: boolean('paidParking').default(false),
  patio: boolean('patio').default(false),
  petFriendly: boolean('petFriendly').default(false),
  piano: boolean('piano').default(false),
  pool: boolean('pool').default(false),
  poolTable: boolean('poolTable').default(false),
  safeBox: boolean('safeBox').default(false),
  ski: boolean('ski').default(false),
  smokeAlarm: boolean('smokeAlarm').default(false),
  smokingAllowed: boolean('smokingAllowed').default(false),
  suitableForEvents: boolean('suitableForEvents').default(false),
  tv: boolean('tv').default(false),
  washer: boolean('washer').default(false),
  wheelchairAccessible: boolean('wheelchairAccessible').default(false),
  wifi: boolean('wifi').default(false),
  yogaOrMeditationSpace: boolean('yogaSpace').default(false),
  createdAt: timestamp('createdAt').defaultNow(),
  updatedAt: timestamp('updatedAt').defaultNow()
})

export type Amenity = typeof amenity
export type AmenityFields = typeof amenity.$inferSelect
