name: Deploy and Test

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Test SSH connection with password
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
        run: |
          sshpass -p $DROPLET_PASSWORD ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP "echo 'SSH connection successful'"

      - name: Deploy to DigitalOcean Droplet
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
        run: |
          sshpass -p $DROPLET_PASSWORD ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP << EOF
            cd /home/hosgu
            if ! command -v npm &> /dev/null
            then
              echo "Node.js and npm not found. Installing..."
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            git pull origin development
            npm stop
            npm install
            npm run db:drop
            npm run db:push
            npm run db:seed
            npm run build
            if [ \$? -ne 0 ]; then
              echo "Build failed. Aborting start."
              exit 1
            fi
            npm start
          EOF

  run-tests:
    needs: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Sleep for 2 minutes
        run: sleep 120

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
